const EMPLOYEE_TITLES = ["operator", "coach", "team leader", "shift leader", "exception handler", "supervisor"]
const EXCEPTION_STATUS = ["handled", "irrecoverable", "replaced", "backlog"]
const ZONES = ["AR"]
const DEPARTMENTS = ["outbound"]
const TASK_TYPES = ["picking", "packing"]
const EXCEPTION_TYPES = ["missing", "damaged"]
const EMPLOYEE_ROLES = ["user", "admin", "superAdmin"]
const RECEIEVED_AS = ["costumer complain", "operation error"]
